### ISSUE TITLE
Binary Messages failing with WebSocket.

### ISSUE THREAD

**Issue by Shane8th** [kerryjiang/SuperSocket#292] opened 2020-03-11 19:35 UTC
There is no need to advance the writer after using Write().
This is causing packet read errors, forcing disconnects due to extra bytes being there when there should not be..

Please remove the line that advances after writing data to the buffer in WebSocketEncoder.cs inside the EncodeBinaryMessage method.

```cs
        public int EncodeBinaryMessage(IBufferWriter<byte> writer, WebSocketMessage pack)
        {
            var head = writer.GetSpan(10);
            head[0] = (byte)((byte)pack.OpCode | 0x80);

            var headLen = WriteLength(ref head, pack.Data.Length);
            
            writer.Advance(headLen);

            foreach (var dataPiece in pack.Data)
            {
                writer.Write(dataPiece.Span);

                //This is the line in question that needs to be removed.
                //writer.Advance(dataPiece.Length);
            }

            return (int)(pack.Data.Length + headLen);
        }
```

**Comment by kerryjiang** [comment] 2020-03-11 20:26
Good finding! I will fix it tonight.

Thanks!

**Comment by Shane8th** [comment] 2020-03-11 22:13
I do have another problem, I can create a new issue if you like.

But, sometimes when there is a lot of messages being processed, message.Data from a websocket will have the correct length, however if you try and use that ReadOnlySequence, it will throw an exception, almost as if its really empty. 

You can easily replicate this if you send some binary messages from a bunch of clients and do something like the following on the server. I have not tried it with text messages.

```cs
builder.ConfigureWebSocketMessageHandler(async (session, message) =>
{
   byte[] data = message.Data.ToArray();
   //do something with this data
});
```

**Comment by kerryjiang** [comment] 2020-03-12 03:39
Did a bug just now:
https://github.com/kerryjiang/SuperSocket/commit/8936962fb41fa5f72da342f073ab53e9058b937e

I will take at look the other problem in this issue.

**Comment by kerryjiang** [comment] 2020-04-17 04:44
@Shane8th I added a test case to reproduce the problem you mentioned. But the test case cannot reproduce it.

Could you tell me more about your case?

https://github.com/kerryjiang/SuperSocket/commit/dac371c442a93f281f3f91b8c658ff36b980cb40

**Comment by Eucly2** [comment] 2020-04-20 08:22
Hello,

I think you can reproduce this problem by sending a big string in JS like this:
`var x = "1234567890";
    var iterations = 10;
    for (var i = 0; i < iterations; i++) {
        x += x + x;
    }`
But i'm not sure if this is the same problem but it's one too because i ahve an error with ReadOnlySequence when i do this

**Comment by kerryjiang** [comment] 2020-04-23 04:24
I made a fix for this issue:
https://github.com/kerryjiang/SuperSocket/commit/db414732de589f1d2000a88ff6c8f18945f8d060
Could you verify if the problem has been fixed in your end?

**Comment by Eucly2** [comment] 2020-04-24 08:48
I don't know if i can say it's ok but i think not.
it's work with the example below but in my project I have to send and receive binary data like pdf file content or images file content and when i try with a pdf for example sometimes i receive a very bad string with no sence, sometime the header is ok like "PDF-1.5" and sometimes i have this error:
 ` Protocol error
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')` at PayloadDataReader.cs:line 24
Maybe some specials caracts make trouble?

**Comment by kerryjiang** [comment] 2020-04-24 15:53
Which version do you use?
Just make sure you use the latest version with the fixes about the binary message.
https://www.nuget.org/packages/SuperSocket.Channel/2.0.0-preview3-04

And I need a way to reproduce this problem easily.

**Comment by kerryjiang** [comment] 2020-04-26 23:34
I did another fix:
https://www.nuget.org/packages/SuperSocket.Channel/2.0.0-preview3-05

**Comment by Eucly2** [comment] 2020-04-27 12:38
Actually, with the 2.0.0-preview3-05 version, I have two problems when I want to transfer pdf file between WSS javascript client and WebSocket CS Server:
- With one pdf file I have an lenght error on the server
- With another one no error but when I construct the file with the received datas I got a bad file

You can reproduce those problems with this project:
[https://drive.lomaco.org/index.php/s/2VmjoS9kl6Xc3PE](url)

**Comment by kerryjiang** [comment] 2020-04-30 06:47
It looks like encoding issue. Why don't you save the binary data directly to file?

And you don't need convert ReadOnlySequence<byte> to byte[] before write. You can write it to file directly without any allocation and decoding/encoding.

**Comment by Eucly2** [comment] 2020-04-30 07:29
Ok I will try without decoding/encoding but what about the lenght error?

**Comment by kerryjiang** [comment] 2020-04-30 07:32
What’s that error?

**Comment by Eucly2** [comment] 2020-04-30 07:35
With the pdf "LenghtError.pdf" I have this error:
`fail: IChannel[0]
      Protocol error
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
   at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData)
   at SuperSocket.ProtoBase.PackagePartsPipelineFilter`1.Filter(SequenceReader`1& reader)
   at SuperSocket.Channel.PipeChannel`1.ReaderBuffer(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at SuperSocket.Channel.PipeChannel`1.ReadPipeAsync(PipeReader reader)`

**Comment by kerryjiang** [comment] 2020-05-06 03:59
I may found two problems.

1) after review the javascript in the html file, I think the client send the pdf as string instead of binary; so at the server side, you shoudl check the message type at first;

2) I probably fixed a bug related with this after the the preview3-05, so could you try the latest source code?

**Comment by Eucly2** [comment] 2020-05-06 07:36
Sorry but I use the preview3-05 and the length error isn't fixed.
After, the message type is always null:
![image](https://user-images.githubusercontent.com/6839257/81148525-bbefe800-8f7c-11ea-89a3-d1710f7e132c.png)
And I tried to send the data as binary (like this ws.send(data, { binary: true });) in JS but it does not work better

**Comment by kerryjiang** [comment] 2020-05-06 08:20
Is it easy for you to use the latest code in the github? I made a fix about WebSocket after I released preview3-05.

**Comment by Eucly2** [comment] 2020-05-06 08:24
Ok I'll try

**Comment by Eucly2** [comment] 2020-05-06 08:43
Ok now I have an error with the first pdf:
`fail: IChannel[0]
      Protocol error
System.InvalidOperationException: End position was not reached during enumeration.
   at System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached()
   at System.Buffers.ReadOnlySequence`1.Enumerator.MoveNext()
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.ConcactSequence(ReadOnlySequence`1& first, ReadOnlySequence`1& second) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.WebSocket\FramePartReader\PayloadDataReader.cs:line 94
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.WebSocket\FramePartReader\PayloadDataReader.cs:line 38
   at SuperSocket.ProtoBase.PackagePartsPipelineFilter`1.Filter(SequenceReader`1& reader) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.ProtoBase\PackagePartsPipelineFilter.cs:line 28
   at SuperSocket.Channel.PipeChannel`1.ReaderBuffer(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.Channel\PipeChannel.cs:line 394
   at SuperSocket.Channel.PipeChannel`1.ReadPipeAsync(PipeReader reader) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.Channel\PipeChannel.cs:line 345`

And alway leght error with the second:
`fail: IChannel[0]
      Protocol error
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
   at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.WebSocket\FramePartReader\PayloadDataReader.cs:line 24
   at SuperSocket.ProtoBase.PackagePartsPipelineFilter`1.Filter(SequenceReader`1& reader) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.ProtoBase\PackagePartsPipelineFilter.cs:line 28
   at SuperSocket.Channel.PipeChannel`1.ReaderBuffer(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.Channel\PipeChannel.cs:line 394
   at SuperSocket.Channel.PipeChannel`1.ReadPipeAsync(PipeReader reader) in D:\Projects\Visual Studio 2015 C#\SuperSocket-master\src\SuperSocket.Channel\PipeChannel.cs:line 345`

**Comment by kerryjiang** [comment] 2020-07-28 05:34
Are you still around?

Try beta4 if yes:
https://www.nuget.org/packages/SuperSocket/2.0.0-beta4

**Comment by Eucly2** [comment] 2020-07-28 08:35
Hi!

Yes I still around and the beta4 doesn't change anything. I always get this error:
`fail: IChannel[0]
      Protocol error
System.InvalidOperationException: End position was not reached during enumeration.
   at System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached()
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.ConcactSequence(ReadOnlySequence`1& first, ReadOnlySequence`1& second)
   at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData)
   at SuperSocket.ProtoBase.PackagePartsPipelineFilter`1.Filter(SequenceReader`1& reader)
   at SuperSocket.Channel.PipeChannel`1.ReaderBuffer(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at SuperSocket.Channel.PipeChannel`1.ReadPipeAsync(PipeReader reader)`

But I find a solution, I split the string every 65536 caract and I send it one by one... It's bad but it's work

**Comment by kerryjiang** [comment] 2020-07-28 19:18
What's the size of the file?

**Comment by Eucly2** [comment] 2020-07-28 19:49
The file size varies between 100kb and 500kb

Le mar. 28 juil. 2020 à 21:18, Kerry Jiang <notifications@github.com> a
écrit :

**Comment by kerryjiang** [comment] 2020-08-09 22:04
Could you try beta5? I wrote a test to cover this case and it does reproduce this problem. I have fixed the bug and just released beta5 which includes this fix.

**Comment by Eucly2** [comment] 2020-08-17 13:40
Hi!

it's work now. Thx

**Closed** 2020-08-19 21:27 UTC
Labels: 2.0, bug
