### ISSUE TITLE
使用 WebSocketMessageType.Binary 传数据发生异常.

### ISSUE THREAD

**Issue by jason-shi** [kerryjiang/SuperSocket#318] opened 2020-04-15 10:55 UTC
江大, 使用 WebSocketMessageType.Binary 类型传递二进制时, 在 PackageMapper<WebSocketPackage, SelfPackage> 中 从WebSocketPackage.Data取数据时, 会出现下面的异常,
Specified argument was out of the range of valid values. (Parameter 'start')

**Comment by jason-shi** [comment] 2020-04-16 13:51
![图片](https://user-images.githubusercontent.com/1249955/79464231-620a9b00-802c-11ea-8ed5-122839e876f0.png)

after add this line, it run ok...

**Comment by jason-shi** [comment] 2020-04-16 13:59
PayloadDataReader.cs
Line 24
var seq = reader.Sequence.Slice(reader.Consumed, required);
// add this line, it run ok
seq = new ReadOnlySequence<byte>(seq.First);            

我加了一条 seq = new ReadOnlySequence<byte>(seq.First);  运行就OK了, 请大神指教

**Comment by kerryjiang** [comment] 2020-04-17 04:28
I just added a test case for binary message. But it works.
Could you add a test which can reproduce this problem?
https://github.com/kerryjiang/SuperSocket/commit/b8f3467f0bf2faa2453fcefee4aca448a92e37c5

**Comment by jason-shi** [comment] 2020-04-17 06:34
I test your test case, it run fine.
but when i change the a varible in xunit.runner.json
"parallelizeTestCollections": true, 
the error occ.
i don't know why...

**Comment by kerryjiang** [comment] 2020-04-17 16:03
Because all the test cases listen on the same ports, so they cannot run at the same time.

**Comment by kerryjiang** [comment] 2020-04-17 16:04
I will add a test case to cover the situation multiple connections communicate with the server concurrently.

**Comment by kerryjiang** [comment] 2020-04-18 20:56
Adjusted the test case to be concurrent connection mode, but works as well.
https://github.com/kerryjiang/SuperSocket/commit/ab467637b749de6e720dd5a5c00a6d3a73c40e8e

I just need a test case to reproduce the problem you mentioned.

**Comment by kerryjiang** [comment] 2020-04-18 21:05
OK, actually I have reproduced this problem.
https://github.com/kerryjiang/SuperSocket/runs/598414469?check_suite_focus=true#step:5:1990

Thank you! I am checking this issue.

**Comment by kerryjiang** [comment] 2020-04-23 04:23
I made a fix for this issue:
https://github.com/kerryjiang/SuperSocket/commit/db414732de589f1d2000a88ff6c8f18945f8d060

Could you verify if the problem has been fixed in your end?

**Comment by kerryjiang** [comment] 2020-04-27 01:38
Just did one more fix, please get the latest version from nuget or github.

**Comment by jason-shi** [comment] 2020-04-30 02:19
nice, it fixed

**Closed** 2020-04-30 02:22 UTC
Labels: 2.0, bug
