### ISSUE TITLE
Calling IChannel.SendAsync results in combined responses

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#461] opened 2020-12-31 14:31 UTC
When I send responses, they have a tendency to get grouped together if they are sent too close to each other. For example the following echo server:
```CSharp
var host = SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>(args)
.UsePackageHandler(async (s, p) =>
{
    await s.SendAsync(Encoding.UTF8.GetBytes("[THIS IS ONE DATAGRAM]"));
    await s.SendAsync(Encoding.UTF8.GetBytes("[THIS IS ANOTHER ONE]"));
})
.ConfigureSuperSocket(options =>
{
    options.Name = "Echo Server";
    options.AddListener(new ListenOptions
    {
        Ip = "Any",
        Port = 11000
    }
    );
})
.UseUdpProtocol()
.Build();

await host.RunAsync();
```

I get the response back "[THIS IS ONE DATAGRAM][THIS IS ANOTHER ONE]" instead of getting them in two separate datagrams. When using UDP and if I access the raw socket underneath and call `SendToAsync` I don't get my datagrams combined. To my understanding this is because of the pipe functionality in Supersocket that buffers up whatever needs to be sent.

**Comment by martinmine** [comment] 2020-12-31 14:48
Looks like this is also relevant for TCP packets

**Comment by martinmine** [comment] 2020-12-31 16:22
Also closing right after sending results in no data being received in the client side:
```Csharp
var host = SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>(args)
.UsePackageHandler(async (s, p) =>
{
    await s.SendAsync(Encoding.UTF8.GetBytes("blah" + Environment.NewLine));
    await s.CloseAsync(CloseReason.LocalClosing);
})
.ConfigureSuperSocket(options =>
{
    options.Name = "Echo Server";
    options.AddListener(new ListenOptions
    {
        Ip = "Any",
        Port = 11000
    }
    );
})
.Build();
```

**Comment by kerryjiang** [comment] 2021-01-01 05:00
The first issue is by design.

I will add a test case for the second problem.

**Comment by martinmine** [comment] 2021-01-01 12:58
@kerryjiang how would you suggest I would approach the problem in my case? Currently I am using reflection to reach the underlying socket. It would be very nice if there could be a way to configure this with a feature flag or some sort so I don't have to hack around with reflection.

**Comment by kerryjiang** [comment] 2021-01-07 09:56
I did a fix for this problem.

**Comment by martinmine** [comment] 2021-01-07 13:41
Excellent! Does a7307af9cd8745ac0e1bee3a9e16bd7308decf02 also address the issue regarding sending / closing right after each other as well?

**Comment by kerryjiang** [comment] 2021-01-07 16:43
Not yet, I will add a test case for that scenario.

**Comment by kerryjiang** [comment] 2021-01-08 08:45
Did a fix but one test case about Udp fails. I will figure it out tomorrow.

**Comment by kerryjiang** [comment] 2021-01-30 07:08
I think this issue had been fixed. I have released SuperSocket 2.0.0-beta.8.

**Closed** 2021-01-30 07:09 UTC
Labels: 2.0, bug

**Comment by martinmine** [comment] 2021-01-30 11:30
@kerryjiang I will have a look, but I don't see any beta-8 on Nuget yet. Could it be because the Github actions build is red?

**Comment by kerryjiang** [comment] 2021-01-30 16:05
No just the version ordering issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinmine** [comment] 2021-01-30 16:46
On nuget.org the last version was 2.0.0-beta7, published 3 months ago: https://www.nuget.org/packages/SuperSocket
2.0.0-beta.8 is not out yet on the nuget feed.

**Comment by kerryjiang** [comment] 2021-01-30 17:11
Over there. I can find it:
https://www.nuget.org/packages/SuperSocket/2.0.0-beta.8


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinmine** [comment] 2021-01-30 17:16
Haha, I guess the . between beta and 8 got me confused as it wasn't on top of the list. Thanks! 😄

**Comment by kerryjiang** [comment] 2021-01-30 19:53
Yes, SemiVer 2.
